"""Add news sanctions and quality tables

Revision ID: 3c2d843c3956
Revises: 3d9523b0f0c4
Create Date: 2025-11-14 20:36:34.235197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c2d843c3956'
down_revision: Union[str, Sequence[str], None] = '3d9523b0f0c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('secid', sa.String(length=32), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=True),
    sa.Column('geo_scope', sa.String(length=32), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('latency_profile', sa.String(length=64), nullable=True),
    sa.Column('ingest_params', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sanction_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_name', sa.String(length=256), nullable=False),
    sa.Column('list_code', sa.String(length=64), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('secid', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sanction_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('secid', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['sanction_entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('global_risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('geo_region', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_event_id', sa.Integer(), nullable=True),
    sa.Column('affected_sectors', sa.JSON(), nullable=True),
    sa.Column('expected_impact_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secid', sa.String(length=32), nullable=True),
    sa.Column('sector_code', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('trigger_reason', sa.String(length=128), nullable=False),
    sa.Column('linked_global_event_id', sa.Integer(), nullable=True),
    sa.Column('decay_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['linked_global_event_id'], ['global_risk_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_alerts')
    op.drop_table('global_risk_events')
    op.drop_table('sanction_links')
    op.drop_table('news_events')
    op.drop_table('sanction_entities')
    op.drop_table('news_sources')
    op.drop_table('data_quality_alerts')
    # ### end Alembic commands ###
