"""Add regime policy and etl tables

Revision ID: 3d9523b0f0c4
Revises: fd8c2dd74ec7
Create Date: 2025-11-14 20:23:06.877092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9523b0f0c4'
down_revision: Union[str, Sequence[str], None] = 'fd8c2dd74ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etl_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows_processed', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_value', sa.String(length=64), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('probabilities_json', sa.JSON(), nullable=True),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regimes_timestamp'), ['timestamp'], unique=False)

    op.create_table('policy_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy_regime_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_code', sa.String(length=64), nullable=False),
    sa.Column('regime_pattern', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('weight_adjustment', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('rules_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_data_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('secid', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('snapshot_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('snapshot_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rows_count', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secid', 'timeframe', 'snapshot_start', 'snapshot_end', name='uq_train_data_snapshots_range')
    )
    op.create_table('market_regime_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_value', sa.String(length=64), nullable=True),
    sa.Column('base_regime_id', sa.Integer(), nullable=False),
    sa.Column('liquidity_regime', sa.String(length=64), nullable=True),
    sa.Column('spread_regime', sa.String(length=64), nullable=True),
    sa.Column('news_burst_level', sa.Integer(), nullable=True),
    sa.Column('derived_from', sa.String(length=64), nullable=True),
    sa.Column('features_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['base_regime_id'], ['market_regimes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_regime_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regime_details_timestamp'), ['timestamp'], unique=False)

    op.create_table('policy_feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_run_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('secid', sa.String(length=32), nullable=True),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('chosen_action', sa.String(length=64), nullable=False),
    sa.Column('reward', sa.Float(), nullable=True),
    sa.Column('reward_components_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_run_id'], ['policy_runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_feedback_policy_run_id'), ['policy_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_policy_feedback_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_feedback_timestamp'))
        batch_op.drop_index(batch_op.f('ix_policy_feedback_policy_run_id'))

    op.drop_table('policy_feedback')
    with op.batch_alter_table('market_regime_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_regime_details_timestamp'))

    op.drop_table('market_regime_details')
    op.drop_table('train_data_snapshots')
    op.drop_table('strategy_regime_policies')
    op.drop_table('policy_runs')
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_regimes_timestamp'))

    op.drop_table('market_regimes')
    op.drop_table('etl_jobs')
    # ### end Alembic commands ###
