"""Add calendar fx macro ofz tables

Revision ID: fd8c2dd74ec7
Revises: 
Create Date: 2025-11-14 20:16:04.946878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8c2dd74ec7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commodity_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timestamp', name='uq_commodity_prices_symbol_ts')
    )
    op.create_table('exchange_calendar',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_trading_day', sa.Boolean(), nullable=False),
    sa.Column('session_open', sa.Time(), nullable=True),
    sa.Column('session_close', sa.Time(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    with op.batch_alter_table('exchange_calendar', schema=None) as batch_op:
        batch_op.create_index('ix_exchange_calendar_is_trading', ['is_trading_day'], unique=False)

    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pair', sa.String(length=16), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pair', 'timestamp', name='uq_fx_rates_pair_ts')
    )
    op.create_table('macro_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_code', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('revision', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_code', 'period_start', 'period_end', name='uq_macro_series_period')
    )
    op.create_table('ofz_auctions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('offered', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('placed', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('yield_min', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('yield_avg', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('yield_max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('bid_cover', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auction_date', 'isin', name='uq_ofz_auctions_isin_date')
    )
    op.create_table('ofz_yields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('maturity_date', sa.Date(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ytm', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('dirty_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('duration', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('convexity', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('coupon', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('next_coupon_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin', 'date', name='uq_ofz_yields_isin_date')
    )
    op.create_table('policy_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rate_code', sa.String(length=32), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rate_code', 'date', name='uq_policy_rates_code_date')
    )
    op.create_table('schedule_changes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_changes_effective_date'), ['effective_date'], unique=False)
        batch_op.create_index('ix_schedule_changes_type', ['change_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_user_id'), ['user_id'], unique=False)

    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('trigger_score', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=True),
    sa.Column('horizon', sa.String(length=32), nullable=True),
    sa.Column('assets_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_results_news_id'), ['news_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_results_news_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_results_id'))

    op.drop_table('analysis_results')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_user_id'))
        batch_op.drop_index(batch_op.f('ix_news_id'))

    op.drop_table('news')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('schedule_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_changes_type')
        batch_op.drop_index(batch_op.f('ix_schedule_changes_effective_date'))

    op.drop_table('schedule_changes')
    op.drop_table('policy_rates')
    op.drop_table('ofz_yields')
    op.drop_table('ofz_auctions')
    op.drop_table('macro_series')
    op.drop_table('fx_rates')
    with op.batch_alter_table('exchange_calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_exchange_calendar_is_trading')

    op.drop_table('exchange_calendar')
    op.drop_table('commodity_prices')
    # ### end Alembic commands ###
